FROM python:3.9-slim-buster

RUN apt-get update && apt-get -y install python3 python3-pip
RUN pip3 install flask mysql-connector-python python-dotenv paramiko

WORKDIR /app

COPY *py /app/
COPY .env /app/

ENTRYPOINT FLASK_APP=/app/app.py flask run --host=0.0.0.0
