FROM php:7.4-apache

RUN apt-get update && apt-get -y install apache2

WORKDIR /var/www/html

COPY index.html /var/www/html/
COPY styles.css /var/www/html/
COPY script.js /var/www/html/

EXPOSE 80

CMD ["apache2-foreground"]